name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  check:
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v4

      - uses: astral-sh/setup-uv@v5

      - run: uv python install 3.13

      - run: uv sync --frozen --group dev

      - run: uv run ruff check .

      - run: uv run mypy .
